name: Release Flow

on:
  release:
    types: [published]

jobs:
  publish-packages:
    name: Push Packages to IPFS
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get autoremove
          sudo apt-get autoclean
          python -m pip install --upgrade pip
          pip install open-autonomy[all]==0.21.16
          pip install "click>=8.3.0,<9"

      - name: Push packages
        run: |
          autonomy init --reset --author valory --ipfs --remote
          autonomy push-all
